import type { HallucinatedSymbol, IssueKind, ModelScore, Report } from './types.js'

const KIND_LABEL: Record<IssueKind, string> = {
  'missing-export': 'no such export',
  'missing-member': 'no such member',
  'wrong-signature': 'wrong arguments',
  'missing-module': 'no such module',
  'type-error': 'misused',
}

export interface FormatOptions {
  color?: boolean
  /** Number of hallucinated symbols to list. Default 10. */
  top?: number
}

type Paint = (text: string) => string

function palette(color: boolean) {
  const wrap =
    (open: number, close: number): Paint =>
    (text) =>
      color ? `\u001b[${open}m${text}\u001b[${close}m` : text
  return {
    bold: wrap(1, 22),
    dim: wrap(2, 22),
    red: wrap(31, 39),
    green: wrap(32, 39),
    yellow: wrap(33, 39),
    cyan: wrap(36, 39),
  }
}

const plural = (n: number, word: string): string => `${n} ${word}${n === 1 ? '' : 's'}`

export const percent = (score: number): string => `${Math.round(score * 100)}%`

function bar(score: number, width = 20): string {
  const filled = Math.round(score * width)
  return '█'.repeat(filled) + '░'.repeat(width - filled)
}

function scoreColor(score: number, p: ReturnType<typeof palette>): Paint {
  if (score >= 0.9) return p.green
  if (score >= 0.7) return p.yellow
  return p.red
}

function modelLine(m: ModelScore, width: number, p: ReturnType<typeof palette>): string {
  const paint = scoreColor(m.score, p)
  const notes = [
    m.byStatus.refused && `${m.byStatus.refused} refused`,
    m.byStatus.error && `${m.byStatus.error} errors`,
    m.byStatus['no-code'] && `${m.byStatus['no-code']} without code`,
    m.byStatus.unused && `${m.byStatus.unused} ignored the package`,
  ].filter(Boolean)
  const tail = notes.length ? p.dim(`  (${notes.join(', ')})`) : ''
  return `  ${m.model.padEnd(width)}  ${paint(bar(m.score))}  ${paint(percent(m.score).padStart(4))}  ${p.dim(`${m.passed}/${m.graded}`)}${tail}`
}

function hallucinationLine(h: HallucinatedSymbol, width: number, p: ReturnType<typeof palette>) {
  const fix = h.suggestion ? `  ${p.cyan(`→ ${h.suggestion}`)}` : ''
  const models = h.models.length > 1 ? `${h.models.length} models` : (h.models[0] ?? '')
  return `  ${p.red('✗')} ${h.symbol.padEnd(width)}  ${KIND_LABEL[h.kind].padEnd(15)}  ${p.dim(`×${h.count} · ${models}`)}${fix}`
}

export function formatReport(report: Report, options: FormatOptions = {}): string {
  const p = palette(options.color ?? false)
  const top = report.hallucinations.slice(0, options.top ?? 10)
  const sampleCount = Math.max(...report.models.map((m) => m.total), 0)
  const perTask = report.tasks.length ? Math.round(sampleCount / report.tasks.length) : 0

  const lines = [
    '',
    `  ${p.bold('llmknows')} ${p.dim('·')} ${report.package.name}@${report.package.version} ${p.dim(
      `· ${plural(report.tasks.length, 'task')} × ${plural(report.models.length, 'model')} × ${plural(perTask, 'sample')}`,
    )}`,
    '',
    `  ${p.bold('API accuracy')}`,
  ]
  const modelWidth = Math.max(...report.models.map((m) => m.model.length))
  for (const model of report.models) lines.push(modelLine(model, modelWidth, p))

  if (top.length) {
    lines.push('', `  ${p.bold('Most hallucinated APIs')}`)
    const width = Math.min(40, Math.max(...top.map((h) => h.symbol.length)))
    for (const h of top) lines.push(hallucinationLine(h, width, p))
  } else {
    lines.push('', `  ${p.green('No hallucinated APIs found.')}`)
  }
  lines.push('')
  return lines.join('\n')
}

/** Markdown notes for AGENTS.md / llms.txt that correct what models get wrong. */
export function formatFix(report: Report, options: { top?: number } = {}): string {
  const { name, version } = report.package
  const items = report.hallucinations.slice(0, options.top ?? 15)
  const lines = [
    `## Using ${name} (v${version})`,
    '',
    `AI models often get these \`${name}\` APIs wrong. They do not exist or are used incorrectly in v${version}:`,
    '',
  ]
  if (items.length === 0) lines.push('- No common mistakes found.')
  for (const h of items) {
    const what =
      h.kind === 'wrong-signature'
        ? `\`${h.symbol}\` is called with the wrong arguments`
        : h.kind === 'type-error'
          ? `\`${h.symbol}\` is misused`
          : `\`${h.symbol}\` does not exist`
    lines.push(`- ${what}${h.suggestion ? ` — use \`${h.suggestion}\` instead.` : '.'}`)
  }
  lines.push('', `<!-- generated by llmknows on ${report.createdAt.slice(0, 10)} -->`, '')
  return lines.join('\n')
}

// Approximate Verdana 11px glyph widths, close enough for shields-style badges.
function textWidth(text: string): number {
  let width = 0
  for (const ch of text) {
    if ('ijl.,:;!|\'"'.includes(ch)) width += 3.5
    else if ('mwMW%@'.includes(ch)) width += 10
    else if (ch >= 'A' && ch <= 'Z') width += 7.5
    else if (ch === ' ') width += 3.8
    else width += 6.6
  }
  return Math.ceil(width)
}

function escapeXml(text: string): string {
  return text.replace(/[<>&"']/g, (c) => `&#${c.charCodeAt(0)};`)
}

/** A flat, shields.io-style SVG badge: `AI API accuracy | 92%`. */
export function renderBadge(score: number, label = 'AI API accuracy'): string {
  const value = percent(score)
  const color = score >= 0.9 ? '#2ea043' : score >= 0.7 ? '#d29922' : '#cf222e'
  const lw = textWidth(label) + 12
  const vw = textWidth(value) + 12
  const w = lw + vw
  const l = escapeXml(label)
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="20" role="img" aria-label="${l}: ${value}"><title>${l}: ${value}</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="${w}" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="${lw}" height="20" fill="#555"/><rect x="${lw}" width="${vw}" height="20" fill="${color}"/><rect width="${w}" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11"><text x="${lw / 2}" y="15" fill="#010101" fill-opacity=".3">${l}</text><text x="${lw / 2}" y="14">${l}</text><text x="${lw + vw / 2}" y="15" fill="#010101" fill-opacity=".3">${value}</text><text x="${lw + vw / 2}" y="14">${value}</text></g></svg>\n`
}

/** Score shown on the badge: the average over all models that produced gradable answers. */
export function overallScore(report: Report): number {
  const graded = report.models.filter((m) => m.graded > 0)
  if (graded.length === 0) return 0
  return graded.reduce((sum, m) => sum + m.score, 0) / graded.length
}
